name: Complete Test Suite

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - api
        - visual
        - smoke
        - regression

jobs:
  api-tests:
    name: API Test Suite
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'api'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Run All API Tests
      run: |
        echo "Running comprehensive API test suite..."
        mvn clean test -Dtest=TestRunner -Dcucumber.filter.tags="@api"

    - name: Upload API Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: api-test-results-${{ github.run_number }}
        path: |
          target/cucumber-reports/
          src/test/resources/reports/

  smoke-tests:
    name: Smoke Test Suite
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'smoke'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Run Smoke Tests (API Only)
      run: |
        echo "Running smoke tests (API only - no mobile UI in CI)..."
        mvn test -Dtest=TestRunner -Dcucumber.filter.tags="@smoke and @api"

    - name: Upload Smoke Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: smoke-test-results-${{ github.run_number }}
        path: |
          target/cucumber-reports/
          src/test/resources/reports/

  regression-tests:
    name: Regression Test Suite
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'regression'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Run Regression Tests (API Only)
      run: |
        echo "Running regression tests (API only - no mobile UI in CI)..."
        mvn test -Dtest=TestRunner -Dcucumber.filter.tags="@regression and @api"

    - name: Upload Regression Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: regression-test-results-${{ github.run_number }}
        path: |
          target/cucumber-reports/
          src/test/resources/reports/

  notify-results:
    name: Notify Test Results
    runs-on: ubuntu-latest
    needs: [api-tests, smoke-tests, regression-tests]
    if: always()

    steps:
    - name: Create summary and send Discord notification
      run: |
        # Create GitHub summary
        echo "## 📊 Test Suite Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Test Type | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY

        # Prepare Discord message data
        DISCORD_FIELDS=""
        OVERALL_STATUS="success"

        # API Tests
        if [ "${{ needs.api-tests.result }}" == "success" ]; then
          echo "| API Tests | ✅ PASSED |" >> $GITHUB_STEP_SUMMARY
          API_STATUS="✅ PASSED"
        else
          echo "| API Tests | ❌ FAILED |" >> $GITHUB_STEP_SUMMARY
          API_STATUS="❌ FAILED"
          OVERALL_STATUS="failure"
        fi

        # Smoke Tests
        if [ "${{ needs.smoke-tests.result }}" == "success" ]; then
          echo "| Smoke Tests | ✅ PASSED |" >> $GITHUB_STEP_SUMMARY
          SMOKE_STATUS="✅ PASSED"
        else
          echo "| Smoke Tests | ❌ FAILED |" >> $GITHUB_STEP_SUMMARY
          SMOKE_STATUS="❌ FAILED"
          OVERALL_STATUS="failure"
        fi

        # Regression Tests
        if [ "${{ needs.regression-tests.result }}" == "success" ]; then
          echo "| Regression Tests | ✅ PASSED |" >> $GITHUB_STEP_SUMMARY
          REGRESSION_STATUS="✅ PASSED"
        else
          echo "| Regression Tests | ❌ FAILED |" >> $GITHUB_STEP_SUMMARY
          REGRESSION_STATUS="❌ FAILED"
          OVERALL_STATUS="failure"
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📋 **Test Reports:** Available in GitHub Actions artifacts" >> $GITHUB_STEP_SUMMARY
        echo "🕒 **Run Time:** $(date)" >> $GITHUB_STEP_SUMMARY

        # Prepare Discord notification
        if [ "$OVERALL_STATUS" == "success" ]; then
          COLOR="3066993"
          STATUS_EMOJI="✅"
          STATUS_TEXT="COMPLETED"
          DESCRIPTION="Complete test suite finished successfully! 🎉"
        else
          COLOR="15158332"
          STATUS_EMOJI="❌"
          STATUS_TEXT="FAILED"
          DESCRIPTION="Some tests in the complete test suite failed."
        fi

        # Send Discord notification
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{
               \"embeds\": [{
                 \"title\": \"${STATUS_EMOJI} Complete Test Suite - ${STATUS_TEXT}\",
                 \"description\": \"${DESCRIPTION}\",
                 \"color\": ${COLOR},
                 \"fields\": [
                   {
                     \"name\": \"Repository\",
                     \"value\": \"${{ github.repository }}\",
                     \"inline\": true
                   },
                   {
                     \"name\": \"Trigger\",
                     \"value\": \"${{ github.event_name }}\",
                     \"inline\": true
                   },
                   {
                     \"name\": \"Test Type\",
                     \"value\": \"${{ github.event.inputs.test_type || 'scheduled' }}\",
                     \"inline\": true
                   },
                   {
                     \"name\": \"API Tests\",
                     \"value\": \"${API_STATUS}\",
                     \"inline\": true
                   },
                   {
                     \"name\": \"Smoke Tests\",
                     \"value\": \"${SMOKE_STATUS}\",
                     \"inline\": true
                   },
                   {
                     \"name\": \"Regression Tests\",
                     \"value\": \"${REGRESSION_STATUS}\",
                     \"inline\": true
                   },
                   {
                     \"name\": \"Artifacts\",
                     \"value\": \"📊 Test reports available in GitHub Actions\",
                     \"inline\": false
                   }
                 ],
                 \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
               }]
             }" \
             https://discord.com/api/webhooks/1418989799444054036/EaHp_OVJAnpziDcfqdhyyBEZ8Bnuhu4e8ez-BHbdLy5pBMavIjqZ3pTIM12NHlMm0JjW